# Generated by Django 3.2.4 on 2021-08-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
