# Generated by Django 3.2.4 on 2021-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0002_auto_20210825_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
