# Generated by Django 3.2.4 on 2021-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0003_auto_20210825_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_guest',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_reminder',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_task',
            field=models.TextField(max_length=80, null=True),
        ),
    ]
