# Generated by Django 3.2.4 on 2021-08-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0004_auto_20210825_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
