# Generated by Django 3.2.4 on 2021-09-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0005_auto_20210826_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_guest',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_reminder',
        ),
    ]
