# Generated by Django 3.2.4 on 2021-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0006_auto_20210909_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_duration',
            field=models.TimeField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default=' SOME STRING', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_task',
            field=models.TextField(default='SOME STRING', max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='SOME STRING'),
        ),
    ]
