# Generated by Django 3.2.4 on 2021-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='SOME STRING', max_length=20)),
                ('course_trainer', models.CharField(default='SOME STRING', max_length=12)),
                ('course_code', models.CharField(default=0, max_length=12)),
                ('course_description', models.FileField(null=True, upload_to='documents/')),
                ('course_duration', models.PositiveSmallIntegerField(default=0)),
                ('syllabus', models.TextField(max_length=700, null=True)),
            ],
        ),
    ]
