# Generated by Django 3.2.4 on 2021-08-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
