# Generated by Django 3.2.4 on 2021-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.FileField(default='SOME STRING', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.PositiveSmallIntegerField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_trainer',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(default='SOME STRING', max_length=700),
        ),
    ]
