# Generated by Django 3.2.4 on 2021-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='SOME STRING', max_length=12)),
                ('last_name', models.CharField(default='SOME STRING', max_length=12)),
                ('age', models.PositiveSmallIntegerField(default=25)),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'male'), ('3', 'none')], default='SOME STRING', max_length=8)),
                ('bio', models.TextField(default='SOME STRING', max_length=700)),
                ('email_address', models.EmailField(default='SOME STRING', max_length=254)),
                ('phone_number', models.CharField(default='SOME STRING', max_length=12)),
                ('salary', models.PositiveBigIntegerField(default=400)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('contract', models.FileField(null=True, upload_to='documents/')),
                ('date_hired', models.DateField(null=True)),
            ],
        ),
    ]
