# Generated by Django 3.2.4 on 2021-09-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='SOME STRING', max_length=12)),
                ('last_name', models.CharField(default='SOME STRING', max_length=12)),
                ('age', models.PositiveSmallIntegerField(default=19)),
                ('date_of_birth', models.DateField(null=True)),
                ('national_id', models.CharField(max_length=20, null=True)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('nationality', models.CharField(choices=[('1', 'Rwandan'), ('2', 'Kenyan'), ('3', 'Ugandan'), ('4', 'South Sudanese'), ('5', 'Sudanese')], default='SOME STRING', max_length=15)),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'male'), ('3', 'none')], default='SOME STRING', max_length=8)),
                ('guardian_name', models.CharField(default='SOME STRING', max_length=12)),
                ('email_address', models.EmailField(default='SOME STRING', max_length=254)),
                ('district', models.CharField(default='SOME STRING', max_length=12)),
                ('phone_number', models.CharField(default='SOME STRING', max_length=12)),
                ('medical_report', models.FileField(default='SOME STRING', upload_to='documents/')),
                ('date_of_enrollment', models.DateTimeField(null=True)),
                ('course_name', models.CharField(default='SOME STRING', max_length=18)),
                ('languages', models.CharField(choices=[('1', 'English'), ('2', 'Kinyarwanda'), ('3', 'French'), ('4', 'Kiswahili'), ('5', 'Luganda')], default='SOME STRING', max_length=20)),
                ('laptop_number', models.CharField(blank=True, default=1, max_length=10)),
            ],
        ),
    ]
