# Generated by Django 3.2.4 on 2021-09-30 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210812_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_name',
            field=models.CharField(default='SOME STRING', max_length=18),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_enrollment',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'male'), ('3', 'none')], default='SOME STRING', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Kinyarwanda'), ('3', 'French'), ('4', 'Kiswahili'), ('5', 'Luganda')], default='SOME STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='laptop_number',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(default='SOME STRING', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('1', 'Rwandan'), ('2', 'Kenyan'), ('3', 'Ugandan'), ('4', 'South Sudanese'), ('5', 'Sudanese')], default='SOME STRING', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
